### ISSUE TITLE
Bug when scrolling the calendar v1.1.5

### ISSUE THREAD

**Issue by tonyannick** [Mulham-Raee/Horizontal-Calendar#27]
I got this error when i'm scrolling the calendar.

`java.lang.ArrayIndexOutOfBoundsException: length=1021; index=-1
                                                                              at java.util.ArrayList.get(ArrayList.java:306)
                                                                              at devs.mulham.horizontalcalendar.HorizontalCalendarAdapter$1.onClick(HorizontalCalendarAdapter.java:57)
                                                                              at android.view.View.performClick(View.java:4091)
                                                                              at android.view.View$PerformClick.run(View.java:17072)
                                                                              at android.os.Handler.handleCallback(Handler.java:615)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                              at android.os.Looper.loop(Looper.java:153)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:4987)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:511)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
                                                                              at dalvik.system.NativeStart.main(Native Method)`

**Comment by barbeu** [comment]
This bug is fixed in version 1.1.7
