### ISSUE TITLE
The app crashes while the activity is launching

### ISSUE THREAD

**Issue by Abh009** [Mulham-Raee/Horizontal-Calendar#68]
I was trying this library as per the readme.md
I added that dependency and the repository jcenter() already existed
In the layout file I added the tag as given in the readme

### Actual Behavior
> The app crashes while the activity is loading
```
FATAL EXCEPTION: main
                                                                            Process: xyz.xenial.abhinav.dataentry, PID: 5881
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.xenial.abhinav.dataentry/xyz.xenial.abhinav.dataentry.InvestDailyActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:286)
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                                at xyz.xenial.abhinav.dataentry.InvestDailyActivity.onCreate(InvestDailyActivity.java:21)
                                                                                at android.app.Activity.performCreate(Activity.java:6259)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                             Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:286) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                at xyz.xenial.abhinav.dataentry.InvestDailyActivity.onCreate(InvestDailyActivity.java:21) 
                                                                                at android.app.Activity.performCreate(Activity.java:6259) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "devs.mulham.horizontalcalendar.HorizontalCalendarView" on path: DexPathList[[zip file "/data/app/xyz.xenial.abhinav.dataentry-2/base.apk"],nativeLibraryDirectories=[/data/app/xyz.xenial.abhinav.dataentry-2/lib/arm, /vendor/lib, /system/lib]]
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                at android.view.LayoutInflater.createView(LayoutInflater.java:583)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                                at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                                at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                                at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                                at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                                at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:286) 
                                                                                at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                                at xyz.xenial.abhinav.dataentry.InvestDailyActivity.onCreate(InvestDailyActivity.java:21) 
                                                                                at android.app.Activity.performCreate(Activity.java:6259) 
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490) 
                                                                                at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:148) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5443) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
                                                                            	Suppressed: java.lang.NoClassDefFoundError: devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                                at dalvik.system.DexFile.defineClassNative(Native Method)
                                                                                at dalvik.system.DexFile.defineClass(DexFile.java:226)
                                                                                at dalvik.system.DexFile.loadClassBinaryName(DexFile.java:219)
                                                                                at dalvik.system.DexPathList.findClass(DexPathList.java:338)
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:54)
                                                                                		... 25 more
                                                                            	Suppressed: java.lang.ClassNotFoundException: devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                                at java.lang.Class.classForName(Native Method)
                                                                                at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                		... 24 more
                                                                             Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by iqab** [comment]
06-08 11:12:34.313 6959-6959/e.naeemiqab.weekcalender E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: e.naeemiqab.weekcalender, PID: 6959
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{e.naeemiqab.weekcalender/e.naeemiqab.weekcalender.MainActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2804)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                            at android.os.Looper.loop(Looper.java:156)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6623)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                         Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                         Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "devs.mulham.horizontalcalendar.HorizontalCalendarView" on path: DexPathList[[zip file "/data/app/e.naeemiqab.weekcalender-2/base.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_dependencies_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_0_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_1_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_2_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_3_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_4_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_5_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_6_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_7_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_8_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/e.naeemiqab.weekcalender-2/lib/arm, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:616)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:798)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:738)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:869)
                                                                            at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:832)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                            at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                            at e.naeemiqab.weekcalender.MainActivity.onCreate(MainActivity.java:32)
                                                                            at android.app.Activity.performCreate(Activity.java:6910)
                                                                            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2757)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2875)
                                                                            at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1578)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                            at android.os.Looper.loop(Looper.java:156)
06-08 11:12:34.314 6959-6959/e.naeemiqab.weekcalender E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:6623)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
                                                                        	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/widget/RecyclerView;
                                                                            at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                            at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                                                                            		... 24 more
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v7.widget.RecyclerView" on path: DexPathList[[zip file "/data/app/e.naeemiqab.weekcalender-2/base.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_dependencies_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_0_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_1_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_2_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_3_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_4_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_5_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_6_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_7_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_8_apk.apk", zip file "/data/app/e.naeemiqab.weekcalender-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/e.naeemiqab.weekcalender-2/lib/arm, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                            		... 27 more

**Comment by Kamosko** [comment]
Can you solve it? Thanks

**Comment by jmcoder1** [comment]
I've had the same problem

**Comment by sharathchandrapsn** [comment]
same issue.....can any one help me to resolve this!!!

**Comment by sharathchandrapsn** [comment]
Caused by: android.view.InflateException: Binary XML file line #9: Binary XML file line #9: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView

**Comment by aalap03** [comment]
this is because of using this library in project supporting andoridX, this library is not working with androidX even after enabling jetifier in gradle.properties.
